<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Persona\Module'                        => __DIR__ . '/Module.php',
    'Persona\Controller\IndexController' => __DIR__ . '/src/Persona/Controller/IndexController.php',
);